// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DarkAscendanceProtos.proto

package com.dumptruckman.darkascendance.network.protos;

public final class DarkAscendanceProtos {
  private DarkAscendanceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string testMessage = 1;
    /**
     * <code>required string testMessage = 1;</code>
     */
    boolean hasTestMessage();
    /**
     * <code>required string testMessage = 1;</code>
     */
    java.lang.String getTestMessage();
    /**
     * <code>required string testMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getTestMessageBytes();
  }
  /**
   * Protobuf type {@code com.dumptruckman.darkascendance.network.protos.Test}
   */
  public static final class Test extends
      com.google.protobuf.GeneratedMessage
      implements TestOrBuilder {
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test defaultInstance;
    public static Test getDefaultInstance() {
      return defaultInstance;
    }

    public Test getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              testMessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.class, com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.Builder.class);
    }

    public static com.google.protobuf.Parser<Test> PARSER =
        new com.google.protobuf.AbstractParser<Test>() {
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string testMessage = 1;
    public static final int TESTMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object testMessage_;
    /**
     * <code>required string testMessage = 1;</code>
     */
    public boolean hasTestMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string testMessage = 1;</code>
     */
    public java.lang.String getTestMessage() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          testMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string testMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTestMessageBytes() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      testMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTestMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTestMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTestMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dumptruckman.darkascendance.network.protos.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.class, com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.Builder.class);
      }

      // Construct using com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        testMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor;
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test getDefaultInstanceForType() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.getDefaultInstance();
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test build() {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test buildPartial() {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test result = new com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testMessage_ = testMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test) {
          return mergeFrom((com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test other) {
        if (other == com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test.getDefaultInstance()) return this;
        if (other.hasTestMessage()) {
          bitField0_ |= 0x00000001;
          testMessage_ = other.testMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string testMessage = 1;
      private java.lang.Object testMessage_ = "";
      /**
       * <code>required string testMessage = 1;</code>
       */
      public boolean hasTestMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public java.lang.String getTestMessage() {
        java.lang.Object ref = testMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          testMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTestMessageBytes() {
        java.lang.Object ref = testMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder setTestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder clearTestMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testMessage_ = getDefaultInstance().getTestMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder setTestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.dumptruckman.darkascendance.network.protos.Test)
    }

    static {
      defaultInstance = new Test(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dumptruckman.darkascendance.network.protos.Test)
  }

  public interface Test2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string testMessage = 1;
    /**
     * <code>required string testMessage = 1;</code>
     */
    boolean hasTestMessage();
    /**
     * <code>required string testMessage = 1;</code>
     */
    java.lang.String getTestMessage();
    /**
     * <code>required string testMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getTestMessageBytes();

    // required string testMessage2 = 2;
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    boolean hasTestMessage2();
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    java.lang.String getTestMessage2();
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTestMessage2Bytes();
  }
  /**
   * Protobuf type {@code com.dumptruckman.darkascendance.network.protos.Test2}
   */
  public static final class Test2 extends
      com.google.protobuf.GeneratedMessage
      implements Test2OrBuilder {
    // Use Test2.newBuilder() to construct.
    private Test2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test2 defaultInstance;
    public static Test2 getDefaultInstance() {
      return defaultInstance;
    }

    public Test2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              testMessage_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              testMessage2_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.class, com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.Builder.class);
    }

    public static com.google.protobuf.Parser<Test2> PARSER =
        new com.google.protobuf.AbstractParser<Test2>() {
      public Test2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string testMessage = 1;
    public static final int TESTMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object testMessage_;
    /**
     * <code>required string testMessage = 1;</code>
     */
    public boolean hasTestMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string testMessage = 1;</code>
     */
    public java.lang.String getTestMessage() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          testMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string testMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTestMessageBytes() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string testMessage2 = 2;
    public static final int TESTMESSAGE2_FIELD_NUMBER = 2;
    private java.lang.Object testMessage2_;
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    public boolean hasTestMessage2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    public java.lang.String getTestMessage2() {
      java.lang.Object ref = testMessage2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          testMessage2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string testMessage2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTestMessage2Bytes() {
      java.lang.Object ref = testMessage2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testMessage2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      testMessage_ = "";
      testMessage2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTestMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTestMessage2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTestMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTestMessage2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTestMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTestMessage2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dumptruckman.darkascendance.network.protos.Test2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.class, com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.Builder.class);
      }

      // Construct using com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        testMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        testMessage2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor;
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 getDefaultInstanceForType() {
        return com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.getDefaultInstance();
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 build() {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 buildPartial() {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 result = new com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testMessage_ = testMessage_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.testMessage2_ = testMessage2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2) {
          return mergeFrom((com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 other) {
        if (other == com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2.getDefaultInstance()) return this;
        if (other.hasTestMessage()) {
          bitField0_ |= 0x00000001;
          testMessage_ = other.testMessage_;
          onChanged();
        }
        if (other.hasTestMessage2()) {
          bitField0_ |= 0x00000002;
          testMessage2_ = other.testMessage2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestMessage()) {
          
          return false;
        }
        if (!hasTestMessage2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dumptruckman.darkascendance.network.protos.DarkAscendanceProtos.Test2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string testMessage = 1;
      private java.lang.Object testMessage_ = "";
      /**
       * <code>required string testMessage = 1;</code>
       */
      public boolean hasTestMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public java.lang.String getTestMessage() {
        java.lang.Object ref = testMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          testMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTestMessageBytes() {
        java.lang.Object ref = testMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder setTestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder clearTestMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testMessage_ = getDefaultInstance().getTestMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage = 1;</code>
       */
      public Builder setTestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }

      // required string testMessage2 = 2;
      private java.lang.Object testMessage2_ = "";
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public boolean hasTestMessage2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public java.lang.String getTestMessage2() {
        java.lang.Object ref = testMessage2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          testMessage2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTestMessage2Bytes() {
        java.lang.Object ref = testMessage2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testMessage2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public Builder setTestMessage2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        testMessage2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public Builder clearTestMessage2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testMessage2_ = getDefaultInstance().getTestMessage2();
        onChanged();
        return this;
      }
      /**
       * <code>required string testMessage2 = 2;</code>
       */
      public Builder setTestMessage2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        testMessage2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.dumptruckman.darkascendance.network.protos.Test2)
    }

    static {
      defaultInstance = new Test2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.dumptruckman.darkascendance.network.protos.Test2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dumptruckman_darkascendance_network_protos_Test_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_dumptruckman_darkascendance_network_protos_Test2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032DarkAscendanceProtos.proto\022.com.dumptr" +
      "uckman.darkascendance.network.protos\"\033\n\004" +
      "Test\022\023\n\013testMessage\030\001 \002(\t\"2\n\005Test2\022\023\n\013te" +
      "stMessage\030\001 \002(\t\022\024\n\014testMessage2\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_dumptruckman_darkascendance_network_protos_Test_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dumptruckman_darkascendance_network_protos_Test_descriptor,
              new java.lang.String[] { "TestMessage", });
          internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_dumptruckman_darkascendance_network_protos_Test2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_dumptruckman_darkascendance_network_protos_Test2_descriptor,
              new java.lang.String[] { "TestMessage", "TestMessage2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
